COMMENT =			OpenPGP facilities in Python through the Sequoia PGP library

MODPY_DISTV =		0.1.35
DISTNAME =			pysequoia-${MODPY_DISTV}
PKGNAME =			py-${DISTNAME}
CATEGORIES =		security devel

HOMEPAGE =			https://github.com/wiktor-k/pysequoia

MAINTAINER =		c2qd

# Apache 2.0
PERMIT_PACKAGE =	Yes

MODULES =			lang/python
MODPY_PI =			Yes
MODPY_PYBUILD =		maturin
MODPY_PYTEST =		Yes

.include "crates.inc"

.include <bsd.port.mk>
